---
- hosts: ubuntu
  vars:
    - ansible_sudo_pass: "babel2018"
  tasks:
    - name: ping
      ping:
    - name: Docker-PY
      pip:
        name: "{{ item }}"
      with_items:
      - six==1.4
      - docker-py==1.1.0
    - name: stop elasticsearch3
      docker_container:
        name: elasticsearch3
        state: stopped
