---
- hosts: ubuntu
  vars:
    - ansible_sudo_pass: gina2018
  tasks:
    - name: ping
      ping:
    - name: stop elasticsearch3
      docker:
        name: elasticsearch3
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
        state: stopped
